### PR TITLE
Adds Dockerfiles for CPUs as well as GPUs, closes #29

### LINKED ISSUE #29: Provide nvidia-docker Dockerfile for easy GPU environment setup
We should provide a Dockerfile with the latest NVIDIA GPU drivers, the latest CUDA and cuDNN.

These docker containers can then be started via the `nvidia-docker` plugin to abstract away driver differences on the host which allows users to more easily getting started without manually having to go through the painful NVIDIA driver and package situation.

The goal here is to provide a self-contained Docker image for users ready to run the toolchain.

Tasks:
- [ ] Write Dockerfile for nvidia-docker plugin
- [ ] Install NVIDIA drivers, CUDA, cuDNN
- [ ] Install RoboSat deps. and make binaries `docker run`-able
- [ ] Test
- [ ] Write docs
- [ ] Set up [automated Docker Hub builds](https://docs.docker.com/docker-hub/builds/#link-to-a-hosted-repository-service)

### PR DESCRIPTION
**Pull request by daniel-j-h**
Dockerfiles for CPU as well as GPU images.

### CODE REVIEW

**Comment by daniel-j-h** [comment]
@sshuair let me know if that works for you. I would like to keep these as simple as possible with a single responsibility: packaging up robosat and it's native dependencies for either CPUs or GPUs.

**Comment by sshuair** [comment]
Ok, I will simplify the Docker file. Is it necessary to provide the different cuda version docker image? both CUDA9.0 and CUDA9.1

**Comment by daniel-j-h** [comment]
Hm, good question. I think we can go with the latest versions working with PyTorch (CUDA 9.1 and cuDNN 7) since nvidia-docker should abstract driver related problems anyway, no?

**Comment by daniel-j-h** [comment]
@sshuair here's how to build and use these containers:

```bash
docker build -t mapbox/robosat:gpu -f docker/Dockerfile.gpu .
docker build -t mapbox/robosat:cpu -f docker/Dockerfile.cpu .
```

```bash
docker run -it mapbox/robosat:gpu nvidia-smi
docker run -it mapbox/robosat:gpu /app/rs -h
docker run -it mapbox/robosat:cpu /app/rs -h
```

I just gave it a try on a AWS p2 box and it seems to work. Anything else we should include in the Dockerfiles or do you think this is already good to go?

**Comment by sshuair** [comment]
I agree with CUDA 9.1.

But when I use your code, I got this error:
```
root@bfca94f5b245:~/robosat# ./rs --help
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/robosat/robosat/tools/__main__.py", line 5, in <module>
    from robosat.tools import (
  File "/root/robosat/robosat/tools/features.py", line 11, in <module>
    from robosat.features.parking import ParkingHandler
  File "/root/robosat/robosat/features/parking.py", line 8, in <module>
    from robosat.features.core import denoise, grow, contours, simplify, featurize, parents_in_hierarchy
  File "/root/robosat/robosat/features/core.py", line 1, in <module>
    import cv2
  File "/usr/local/lib/python3.5/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```
and I fix that by add `libglib2.0-0 `, you can checkout the new version #86

**Comment by sshuair** [comment]
I think it is necessary put the robust code into the docker image.  When we run the image, the robosat code is working directly.

**Comment by daniel-j-h** [comment]
Did you build the Dockerfiles and did you then run them? Because I just did and I'm not seeing the libgthread issue you are seeing. Looks like it's coming from OpenCV so that libglib dependency could make sense.

**Comment by sshuair** [comment]
Yes. I build the modified dockerfiles and run the cpu verison. I got this error. the only different is I add `git` and clone from the github `deps/requirements-lock.txt`. It's weird. 

is there a link I could pull your image?

**Comment by daniel-j-h** [comment]
I spent some time on this and we have automated CPU and GPU now:

https://hub.docker.com/r/mapbox/robosat/tags/

There will be latest images for the master branch and images for specific tags.

The images are quite large right now; we might want to trim them down a bit.

**Pull request merged**
